apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr/.azurecr.io//azure-vote-front
    newTag: 992f047edd31b77be642ae1952f45317591bad95
  - name: ivpkacr/.azurecr.io//azure-vote-back
    newTag: 992f047edd31b77be642ae1952f45317591bad95
resources:
  - manifests.yaml