apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/.azurecr.io//azure-vote-front
    newTag: 
  - name: ivpkacr.azurecr.io/.azurecr.io//azure-vote-back
    newTag: 1.0.1
resources:
  - manifests.yaml