apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azure-vote-front
    newTag: c71d78359a6b6fb86500e81a15316f5abaf32a40
  - name: ivpkacr.azurecr.io/azure-vote-back
    newTag: c71d78359a6b6fb86500e81a15316f5abaf32a40
resources:
  - manifests.yaml
