apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: ed0fd22340bb9a6b6ffdc584c43f1a141d04d313
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: ed0fd22340bb9a6b6ffdc584c43f1a141d04d313
resources:
  - manifests.yaml