apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: 787b30c042546b4031502178a1e061c0b240520b
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: 787b30c042546b4031502178a1e061c0b240520b
resources:
  - manifests.yaml