apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: latest
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: latest
resources:
  - manifests.yaml
