apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: 7431f52e73c0f76cf5d8fe629e78362ffd3612d6
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: 7431f52e73c0f76cf5d8fe629e78362ffd3612d6
resources:
  - manifests.yaml