apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io//azure-vote-front
    newTag: 12293677193681294cf13fd6ee5b76db49f149c4
  - name: ivpkacr.azurecr.io//azure-vote-back
    newTag: 12293677193681294cf13fd6ee5b76db49f149c4
resources:
  - manifests.yaml