apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/.azurecr.io//azure-vote-front
    newTag: 1952ad66dd71bb139ff1c6296189f8f0ff3e5afd
  - name: ivpkacr.azurecr.io/.azurecr.io//azure-vote-back
    newTag: 1952ad66dd71bb139ff1c6296189f8f0ff3e5afd
resources:
  - manifests.yaml