apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr/azure-vote-front
    newTag: d0174b0994817211cfa8afe274c453e68bc29094
  - name: ivpkacr/azure-vote-back
    newTag: d0174b0994817211cfa8afe274c453e68bc29094
resources:
  - manifests.yaml