apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: 25057b63369ab419fe8d2bbd137b868aa03a76d2
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: 25057b63369ab419fe8d2bbd137b868aa03a76d2
resources:
  - manifests.yaml