apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: 028f6ee18ae9f685bca0c95ac9a3526240021fd2
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: 028f6ee18ae9f685bca0c95ac9a3526240021fd2
resources:
  - manifests.yaml