apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/azvote/azure-vote-front
    newTag: ae62a692f148e76f37487201ead426a698a9e6f8
  - name: ivpkacr.azurecr.io/azvote/azure-vote-back
    newTag: ae62a692f148e76f37487201ead426a698a9e6f8
resources:
  - manifests.yaml