apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io/.azurecr.io//azure-vote-front
    newTag: dc0b67e298d4d8b2c9f3c4853cd3af61a7ea5628
  - name: ivpkacr.azurecr.io/.azurecr.io//azure-vote-back
    newTag: dc0b67e298d4d8b2c9f3c4853cd3af61a7ea5628
resources:
  - manifests.yaml