apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ivpkacr.azurecr.io//azure-vote-front
    newTag: fd6f5493b0bd321e59e7ae13cb367c5b34cbbc8e
  - name: ivpkacr.azurecr.io//azure-vote-back
    newTag: fd6f5493b0bd321e59e7ae13cb367c5b34cbbc8e
resources:
  - manifests.yaml